# Generated by Django 3.2.18 on 2023-04-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_time',
            new_name='created_date',
        ),
    ]
