# Generated by Django 3.2.18 on 2023-05-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_created_time_contact_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_date',)},
        ),
    ]
