# Generated by Django 3.2.18 on 2023-04-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230425_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='puplished_date',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
