# Generated by Django 3.2.18 on 2023-05-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230506_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
