# Generated by Django 3.2.18 on 2023-06-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sunject',
            new_name='subject',
        ),
    ]
